//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorApp.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;time&quot;:1674141735889,&quot;blocks&quot;:[{&quot;id&quot;:&quot;KgrM3aNM-n&quot;,&quot;type&quot;:&quot;header&quot;,&quot;data&quot;:{&quot;text&quot;:&quot;&lt;mark class=\&quot;cdx-marker\&quot;&gt;&lt;a href=\&quot;http://google.com\&quot;&gt;Heylo&lt;/a&gt;&lt;/mark&gt;&quot;,&quot;level&quot;:3}},{&quot;id&quot;:&quot;NaTtEbbeRT&quot;,&quot;type&quot;:&quot;paragraph&quot;,&quot;data&quot;:{&quot;text&quot;:&quot;Heylo World&quot;}},{&quot;id&quot;:&quot;QdqCFpKBAm&quot;,&quot;type&quot;:&quot;list&quot;,&quot;data&quot;:{&quot;style&quot;:&quot;ordered&quot;,&quot;items&quot;:[{&quot;content&quot;:&quot;A: One&quot;,&quot;items&quot;:[{&quot;content&quot;:&quot;B: Two&quot;,&quot;items&quot;:[]}]},{&quot;content&quot;:&quot;A: Three&quot;,&quot;items&quot;:[{&quot;content&quot;:&quot;B: Four&quot;,&quot;items&quot;:[{&quot;content&quot;:&quot;C: Five&quot;,&quot;items&quot;:[]}]},{&quot;content&quot;:&quot;B: Six&quot;,&quot;items&quot;:[]},{&quot;content&quot;:&quot;:  [rest of string was....
        /// </summary>
        internal static string JSON {
            get {
                return ResourceManager.GetString("JSON", resourceCulture);
            }
        }
    }
}
